### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by yohn89** [huacnlee/PokemonGoMove#1]
已成功fake到旧金山，非常感谢作者。
提个建议就是，把web server 绑定到0.0.0.0，这样的话就可以用局域网下的另外一个手机来控制方向了，就不用再电脑上用鼠标点

**Comment by yohn89** [comment]
我试着改了一下代码没能成功，只好用Nginx反代了一发

**Comment by wonderffee** [comment]
不用Nginx还有其它的办法吗？

**Comment by wolflee** [comment]
在 `controller/app.rb` 中加入一行即可
```ruby
set :bind, '0.0.0.0'
```

**Comment by wonderffee** [comment]
就因为这个游戏，昨晚我已经入门了Nginx😂
