### ISSUE TITLE
Update the short description of repo to english

### ISSUE THREAD

**Issue by yan7109** [huacnlee/PokemonGoMove#12]
![image](https://cloud.githubusercontent.com/assets/6434237/16891412/0c4d5796-4aae-11e6-91e8-0b390d15b307.png)

@huacnlee As more oversea users are Star'ing and Fork'ing this repo, it'd make sense to update the short description to English. You can say something like:
Pokemon GO iOS GPS Emulator - NO Jailbreak needed, lets you play the game on your Mac :)

**Comment by SydOps** [comment]
@yan7109 

This is open source project, why not raise pull require for your own request, if you can help directly?
