### ISSUE TITLE
This simulation will let your account be frozen

### ISSUE THREAD

**Issue by dreadlord1110** [huacnlee/PokemonGoMove#13]
I just tried to use this program and succeed. But I cannot get any pokemon from the simulated location, they will jump out of your poke ball and run away. And you cannot get anything from poke stop and fight in gym. Even worse, I cannot do the same thing after turning off the app and use my actual location. So basically what I can do right now is to get my egg hatched.

**Comment by andriko13** [comment]
It happened because the default gpx file starts you out in California. I assume you live far from there, and the PokemonGo people know you couldn't have traveled that far so quickly. Modify the gpx file so you start out in some lat/lon like your house

**Comment by yan7109** [comment]
See README for ban and workaround.
