### ISSUE TITLE
Code Sign error: No provisioning profiles found: No non–expired provisioning profiles were found.

### ISSUE THREAD

**Issue by yhtomitk** [huacnlee/PokemonGoMove#18]
Code Sign error: No provisioning profiles found: No non–expired provisioning profiles were found.

**Comment by steven-zhou** [comment]
in xcode ->General -> identity -> Team  to select your provisioning profiles

**Comment by yhtomitk** [comment]
Hi Steven, thanks for your reply.

after running ./start-web in terminal, I got -bash: ./start-web: No such
file or directory

what should I do?

Thanks,

tim

**Comment by yan7109** [comment]
Make sure  you run ./start-web in the directory where you cloned the repo, run ls to double check
