### ISSUE TITLE
feature request - with init GPS

### ISSUE THREAD

**Issue by SydOps** [huacnlee/PokemonGoMove#19]
So could we have an option with init GPS when `start-web` command? such as:

     ./start-web @123456789,987654321

If the application can automatically detect my current location, will it be another feature?

**Comment by SydOps** [comment]
Seems there are two places saved the GPS initial data: 

PokemonLocation.gpx
controller/views/index.erb

Update the GPS in second file makes the change. Do I have to update in `PokemonLocation.gpx` as well?

**Comment by yan7109** [comment]
Done, pull the latest
./start-web -l 12 -o 45
