### ISSUE TITLE
When i trying to run this program, Xcode notify me this.

### ISSUE THREAD

**Issue by zhousixiang** [huacnlee/PokemonGoMove#21]
An App ID with Identifier 'com.ruby-china.foo' is not available. Please enter a different string.

**Comment by pengqiuyuan** [comment]
+1

**Comment by dkelll** [comment]
What was the fix? I am getting this error as well.

**Comment by diddy81** [comment]
change 'com.ruby-china.foo' to something else ie 'com.dkelll.foo'
