### ISSUE TITLE
今天运行就提示这两个（-> 所在行)错误，现在情况就是GPS并没有被改变，而且程序会死

### ISSUE THREAD

**Issue by zhousixiang** [huacnlee/PokemonGoMove#28]
dyld`dyld_fatal_error:
->  0x12002d088 <+0>: brk    #0x3

**Comment by zhousixiang** [comment]
dyld`_dyld_start:
    0x12002d000 <+0>:   mov    x28, sp
    0x12002d004 <+4>:   and    sp, x28, #0xfffffffffffffff0
    0x12002d008 <+8>:   movz   x0, #0
    0x12002d00c <+12>:  movz   x1, #0
    0x12002d010 <+16>:  stp    x1, x0, [sp, #-16]!
    0x12002d014 <+20>:  mov    x29, sp
    0x12002d018 <+24>:  sub    sp, sp, #16               ; =16 
    0x12002d01c <+28>:  ldr    x0, [x28]
    0x12002d020 <+32>:  ldr    x1, [x28, #8]
    0x12002d024 <+36>:  add    x2, x28, #16              ; =16 
    0x12002d028 <+40>:  adrp   x4, -1
    0x12002d02c <+44>:  add    x4, x4, #0                ; =0 
    0x12002d030 <+48>:  adrp   x3, 48
    0x12002d034 <+52>:  ldr    x3, [x3, #3320]
    0x12002d038 <+56>:  sub    x3, x4, x3
    0x12002d03c <+60>:  mov    x5, sp
    0x12002d040 <+64>:  bl     0x12002d08c               ; dyldbootstrap::start(macho_header const*, int, char const**, long, macho_header const*, unsigned long*)
->  0x12002d044 <+68>:  mov    x16, x0
    0x12002d048 <+72>:  ldr    x1, [sp]
    0x12002d04c <+76>:  cmp    x1, #0                    ; =0 
    0x12002d050 <+80>:  b.ne   0x12002d05c               ; <+92>
    0x12002d054 <+84>:  add    sp, x28, #8               ; =8 
    0x12002d058 <+88>:  br     x16
    0x12002d05c <+92>:  mov    x30, x1
    0x12002d060 <+96>:  ldr    x0, [x28, #8]
    0x12002d064 <+100>: add    x1, x28, #16              ; =16 
    0x12002d068 <+104>: add    x2, x1, x0, lsl #3
    0x12002d06c <+108>: add    x2, x2, #8                ; =8 
    0x12002d070 <+112>: mov    x3, x2
    0x12002d074 <+116>: ldr    x4, [x3]
    0x12002d078 <+120>: add    x3, x3, #8                ; =8 
    0x12002d07c <+124>: cmp    x4, #0                    ; =0 
    0x12002d080 <+128>: b.ne   0x12002d074               ; <+116>
    0x12002d084 <+132>: br     x16

**Comment by zhousixiang** [comment]
游戏里提示 GPS signal not found

**Comment by yan7109** [comment]
http://stackoverflow.com/questions/31160938/iphone-6-plus-simulator-work-ok-except-for-device
You need to clean the derived data

**Comment by zhousixiang** [comment]
谢谢
