### ISSUE TITLE
click-event.scpt: execution error: System Events got an error: “osascript”不允许辅助访问。 (-1719)

### ISSUE THREAD

**Issue by wonderffee** [huacnlee/PokemonGoMove#3]
不知道怎么在"安全性与隐私"——辅助功能里给它加权限

**Comment by wonderffee** [comment]
解决了，需要把运行./start-web的Terminal或者iTerm加进去

**Comment by zetasq** [comment]
@wonderffee 为什么我把Terminal加进去后报错System Events got an error: Can’t get menu item "PokemonLocation" of menu 1 of menu item "Simulate Location" of menu 1 of menu bar item "Debug" of menu bar 1 of process "Xcode". (-1728)

**Comment by wonderffee** [comment]
让焦点集中到Xcode而不是Terminal试一下

**Comment by zetasq** [comment]
@wonderffee 我这里每在网页上点一次剪头，都会自动跳转到xcode。。。然后查看terminal就抱上面的错误。。

**Comment by wonderffee** [comment]
要不就让xcode显示在屏幕的左边，Chrome显示在屏幕的右边，试一下

**Comment by zetasq** [comment]
@wonderffee 我有点怀疑是applescript不能操作xcode。刚刚我尝试用applescript录制对xcode的操作，没有记录任何操作内容。我系统是El Capitan

**Comment by wonderffee** [comment]
你的Xcode名字不叫Xcode？

**Comment by zetasq** [comment]
@wonderffee 是Xcode呀，我点箭头Xcode弹到最前面说明响应applescript了

**Comment by zetasq** [comment]
@huacnlee 我还发现一个问题，我在网页上点箭头后Xcode里的这个GPX文件并没有被修改，不知道是什么原因。

**Comment by wonderffee** [comment]
@zetasq 就是因为出现System Events got an error所以你的GPX文件不会被修改

**Comment by zetasq** [comment]
@wonderffee 我看那个ruby文件里操作是分两步的吧，第一步修改GPX文件，第二步调用applescript刷新xcode模拟的GPS地址。第一步不依赖applescript应该能修改成功的。

**Comment by huacnlee** [comment]
<img width="780" alt="2016-07-14 9 57 22" src="https://cloud.githubusercontent.com/assets/5518/16825685/6206eacc-49a9-11e6-87d2-740cd548ed97.png">

系统设置里面开启 **终端** 和 **脚本编辑器**
