### ISSUE TITLE
旧金山地图精灵分布只有金门大桥那一块有

### ISSUE THREAD

**Issue by Jerome-lara** [huacnlee/PokemonGoMove#31]
一切都正常，唯独你打包的这个精灵分布地图只有旧金山金门大桥门口那一片显示精灵分布，
然后我尝试安装你引用的原作的地图PokemonGo Map，结果地图有，但是上面一个精灵也没显示...

**Comment by yan7109** [comment]
Likely you need to refresh the Python server to make sure the API requests to Niantic are still functional. Their servers are extremely unstable. Otherwise, restart the Python app and see if the issue is fixed.
