### ISSUE TITLE
Not moving in game unless

### ISSUE THREAD

**Issue by diddy81** [huacnlee/PokemonGoMove#32]
hay only way i can get this to fully work is if i run the auto clicker from PokemonGoControllerSuite to keep clicking on the simulate location in Xcode am i doing something wrong or is that how it should work?

**Comment by saoque** [comment]
Same issue here, any solution?

**Comment by maestroi** [comment]
Same issue here it says 
`click-event.scpt: execution error: System Events got an error: Can’t get menu item "PokemonLocation" of menu 1 of menu item "Simulate Location" of menu 1 of menu bar item "Debug" of menu bar 1 of process "Xcode". (-1728)`

**Comment by dkelll** [comment]
Same issue here as well.

**Comment by diddy81** [comment]
managed to get game to move by looking [here ](http://stackoverflow.com/questions/10140334/applescript-system-events-error-access-for-assistive-devices-is-disabled)
tick the checkbox for terminal 
you also need to install google chrome <--- this needs adding to the readme

**Comment by yan7109** [comment]
updated readme
