### ISSUE TITLE
Failed to code sign "foo". An App ID with Identifier 'com.ruby-china.foo' is not available. Please enter a different string.

### ISSUE THREAD

**Issue by davidworkman9** [huacnlee/PokemonGoMove#33]
Not an iOS developer at all, not sure what I'm missing, I did the steps in the README and getting this when I try to run the app.

**Comment by darrenxyli** [comment]
same issue here

**Comment by diddy81** [comment]
just change 'com.ruby-china.foo' to something else like 'com.pokemonmove.foo'

**Comment by yan7109** [comment]
@diddy81 is correct

**Comment by davidworkman9** [comment]
Kind of correct(works when working with a blank slate), like I said, not familiar with xcode at all so where I change that is not completely obvious, for those that run into that it's under ```Build Settings > Packaging > Product Bundle Identifier```.

Simply changing it after getting this error message does not work. You have to close xcode and reset the xcode project (run ```git checkout foo.xcodeproj/``` in the project root). Then open the project in xcode again, and make the change to the ```Product Bundle Identifier``` then you should be able to run it.
