### ISSUE TITLE
everything running but app not change locations

### ISSUE THREAD

**Issue by fengyuhan** [huacnlee/PokemonGoMove#34]
2 terminal thing is working, and I checked PokemonLocation, Apple Script working just fine, no warning, the file PokemonLocation is able to be modified.

But the game will not update the location, can not figure the reason why? 

Any help?

**Comment by fengyuhan** [comment]
終端兩個都能運行 登錄了谷歌賬戶, 選擇了使用PokemonLocation的選項 在debug里, 然後Apple Script 可以modify gpx 文件 用的瀏覽器是chrome, Accessibility 也沒問題 Local : 3001 裡面一切正常. 就是遊戲中不能移動, 我也試了清除所有location數據和重啟手機, 皆無效.

**Comment by fengyuhan** [comment]
[2016-07-21 00:19:16] INFO  WEBrick 1.3.1
[2016-07-21 00:19:16] INFO  ruby 2.0.0 (2013-06-27) [x86_64-darwin12.4.0]
== Sinatra (v1.4.7) has taken the stage on 3001 for development with backup from WEBrick
[2016-07-21 00:19:16] INFO  WEBrick::HTTPServer#start: pid=6738 port=3001
127.0.0.1 - - [21/Jul/2016 00:19:20] "GET / HTTP/1.1" 200 3886 0.0047
localhost - - [21/Jul/2016:00:19:20 CST] "GET / HTTP/1.1" 200 3886
- -> /
127.0.0.1 - - [21/Jul/2016 00:19:20] "GET /styles/flat-ui.min.css HTTP/1.1" 304 - 0.0005
127.0.0.1 - - [21/Jul/2016 00:19:20] "GET /application.js HTTP/1.1" 304 - 0.0003



later after try many times the code above appears

**Comment by fengyuhan** [comment]
finally working , silly me

**Comment by MeStoop** [comment]
How did you get it to work?
