### ISSUE TITLE
InvalidKeyOrUnauthorizedURLMapError

### ISSUE THREAD

**Issue by fengyuhan** [huacnlee/PokemonGoMove#36]
InvalidKeyOrUnauthorizedURLMapError 

how this happened? using too much API ?

**Comment by diddy81** [comment]
guessing because the free API key is valid up to 25,000 map loads per day
create your own google maps key [look here](https://developers.google.com/maps/documentation/javascript/get-api-key#get-an-api-key)
then swap it out at the bottom of the  controller/views/index.erb file

**Comment by ssachtleben** [comment]
You have to click on the link in the browser console, register an key and put it into the same spot as was before: https://github.com/huacnlee/PokemonGoMove/commit/85c5b625b08614b38ec6b972c96b1cb40847b418

It would be nice if the gui supports a input field for the api key.

**Comment by diddy81** [comment]
i tried adding my own key and it seems to have broke the click destination to walk

**Comment by yan7109** [comment]
No API key needed, removed

**Comment by fengyuhan** [comment]
@diddy81  me 2
