### ISSUE TITLE
封号

### ISSUE THREAD

**Issue by jimmy0017** [huacnlee/PokemonGoMove#4]
我朋友说“那个方法亲测可用，但是我试了一下账号就被暂时小黑屋了，不能抓小精灵也不能拿补寄，应该是完全不能互动了。我怀疑再来几次就封号了。。。”

**Comment by yan7109** [comment]
嗯，玩了半个小时也出现这个问题

**Comment by yan7109** [comment]
https://www.reddit.com/r/pokemongo/comments/4ry7my/psa_spoofing_gps_locations_will_get_you_banned/

**Comment by am1993421** [comment]
不知道有什么办法可以不让内存溢出呢

**Comment by XinyuHou** [comment]
如果启动前把坐标弄成现在自己的坐标 这样也会被ban吗？

**Comment by dmczyn** [comment]
坐标不管弄到哪（就算是从很远的地方调回自己的坐标），只要超过一定距离，你的账号就会被soft ban。一般过一段时间就好了，但是不确定是否多次后会被perm ban。

**Comment by XinyuHou** [comment]
我现在是在开之前先查自己周围pokestop的坐标 然后修改坐标再开游戏 只要不动还没被ban 没有试移动会怎么样

**Comment by dmczyn** [comment]
如果进游戏了能够从stop中获取物品的话，就没问题，如果你发现那个stop的圆圈一直在转但是不变色，那就是被soft ban掉了~

**Comment by yan7109** [comment]
see readme for ban and workaround
