### ISSUE TITLE
Option F Not Working

### ISSUE THREAD

**Issue by zhousixiang** [huacnlee/PokemonGoMove#40]
The Red box never moving when i put pin on the map.

**Comment by diddy81** [comment]
since removing the map api key this is the only part i cant get working 
tried adding my own key but that didnt work ether for some reason

**Comment by diddy81** [comment]
ive found that instead of using localhost:3001 if i use my ip 192.168.1.xx:3001 i can get walking working 
i might have to click the map 3 or 4 times but it does start walking
