### ISSUE TITLE
System Events got an error: Can’t get menu item "PokemonLocation" of menu 1 of menu item "Simulate Location" of menu 1 of menu bar item "Debug" of menu bar 1 of process "Xcode". (-1728)

### ISSUE THREAD

**Issue by broccolii** [huacnlee/PokemonGoMove#5]

**Comment by sun-yr** [comment]
same error

**Comment by yan7109** [comment]
![image](https://cloud.githubusercontent.com/assets/6434237/16824931/c0ab7622-4924-11e6-8119-06608de712bf.png)

**Comment by yan7109** [comment]
That needs to be checked off or it won't work.

**Comment by am1993421** [comment]
Message from debugger: Terminated due to Memory Pressure

**Comment by broccolii** [comment]
I know where the problem is. I hide the navigation system. thx @yan7109

**Comment by juancarlosdmz** [comment]
@broccolii what do you mean with navigation system?

**Comment by juancarlosdmz** [comment]
nvm, I got it

**Comment by sppandlkk** [comment]
I have the same issue. Can either one of you tell me what navigation system means or how I can un-hide it? Thanks

**Comment by juancarlosdmz** [comment]
@sppandlkk on Xcode, re-select PokemonLocation location from the top menu, just like the @yan7109 shows in the image
