### ISSUE TITLE
An App ID with identifier is not available

### ISSUE THREAD

**Issue by SaipanDamashii** [huacnlee/PokemonGoMove#50]
It says when I run the foo, that "An App ID with identifier 'com.ruby-china.foo' is not available. Please enter a different string."

What does this mean, and how do I fix it?

**Comment by zekkd** [comment]
Under Xcode just change the name of the Bundle Identifier "com.ruby-china.foo" to something of else.

**Comment by SaipanDamashii** [comment]
Thanks, that got me past it!
