### ISSUE TITLE
Cannot catch a pokemon when running app

### ISSUE THREAD

**Issue by sbitswc** [huacnlee/PokemonGoMove#55]
When I am trying to catch a pokemon on my phone, after throwing ball out waiting it to be catched, they always failed and pokemon went away. no matter how low CP it is. Also can not swap to get supply from pokemonshops.  Is there some one else met similar problem?

both localhost:5000 and localhost:3001 can display right information, and be able to running app on my iphone, checked Debug->pokemon location and enable terminal in the privacy, can moving by input location via website. Everything looks good.

  

Thanks.

**Comment by sbitswc** [comment]
probably got a soft ban, will update later. Suggest start running app with your home/work location, do not move >2k ft every time. 

duration about soft ban
https://www.reddit.com/r/pokemongo/comments/4u0av6/soft_ban_research/

**Comment by dmczyn** [comment]
yes it is a soft ban.

**Comment by yan7109** [comment]
softban
