### ISSUE TITLE
click-event.scpt: execution error: System Events got an error: osascript is not allowed assistive access. (-1719)

### ISSUE THREAD

**Issue by h8rry** [huacnlee/PokemonGoMove#8]
If you see `click-event.scpt: execution error: System Events got an error: osascript is not allowed assistive access. (-1719)`

If on Mac OS X, try:
1. Read this first: https://support.apple.com/en-us/HT202802
2. Enable Terminal in Accessibility in Security and Privacy

**Comment by yan7109** [comment]
not an issue
