### ISSUE TITLE
Just a white screen on my iphone

### ISSUE THREAD

**Issue by subzerofun** [huacnlee/PokemonGoMove#82]
Hey thanks for the project! I got both the python map server and the sinatra web server running - it shows objects on both ports (5000 / 3001). Everything looking fine!

But when i run the XCode project and the app starts on my iphone i just get a white screen... I use OSX 10.10.5 and XCode 7.2, iPhone has iOS 9. I get no errors when i compile the project, have also checked the selection of Simulate Location with PokemonLocation. 

I don´t see what i did wrong... Has anybody else had this error?

**Comment by diddy81** [comment]
thats what it is supposed to do just minimize the white screen app and load pokemon go
